name: isaaclab
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _x86_64-microarch-level=3=2_skylake
  - ampl-asl=1.0.0=h5888daf_2
  - assimp=5.4.1=h8343317_0
  - boost=1.84.0=hb7f781d_7
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.9.9=h06a4308_0
  - casadi=3.6.7=py310h45b02c1_5
  - cli11=2.5.0=h3f2d84a_0
  - cmake=4.1.1=hc85cc9f_0
  - console_bridge=1.0.2=h924138e_1
  - eigen=3.4.0=h00ab1b0_0
  - elfutils=0.193=h849f50c_0
  - expat=2.7.1=h6a678d5_0
  - gdbm=1.18=h0a1914f_2
  - gmp=6.3.0=hac33072_2
  - gnutls=3.8.9=h86084c0_1
  - hpp-fcl=2.4.4=py310h36494c2_5
  - icu=75.1=he02047a_0
  - ipopt=3.14.17=h7fd866c_2
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libarchive=3.8.1=gpl_h98cc613_100
  - libasprintf=0.25.1=h3f43e3d_1
  - libblas=3.9.0=34_h59b9bed_openblas
  - libblasfeo=0.1.4.2=had105d5_300
  - libboost=1.84.0=h6c02f8c_7
  - libboost-devel=1.84.0=h1a2810e_7
  - libboost-headers=1.84.0=ha770c72_7
  - libboost-python=1.84.0=py310ha2bacc8_7
  - libboost-python-devel=1.84.0=py310hb7f781d_7
  - libcblas=3.9.0=34_he106b2a_openblas
  - libcurl=8.14.1=h332b0f4_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libfatrop=0.0.4=h5888daf_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgfortran=15.1.0=h69a702a_4
  - libgfortran-ng=15.1.0=h69a702a_4
  - libgfortran5=15.1.0=hcea5267_4
  - libgomp=15.1.0=h767d61c_4
  - libgrpc=1.71.0=h2d74bed_0
  - libgz-cmake3=3.5.3=hac33072_0
  - libgz-cmake4=4.2.0=h3f2d84a_0
  - libgz-math7=7.5.2=h54a6638_0
  - libgz-tools2=2.0.3=hecca717_0
  - libgz-utils2=2.2.0=h5888daf_1
  - libhwloc=2.11.2=default_h3d81e11_1002
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=ha4ef2c3_0
  - liblapack=3.9.0=34_h7ac8fdf_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libmicrohttpd=1.0.2=hc2fc477_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libosqp=0.6.3=h5888daf_1
  - libprotobuf=5.29.3=h3cdef7c_1
  - libqdldl=0.1.7=hcb278e6_0
  - libre2-11=2024.07.02=h6a678d5_0
  - libscotch=7.0.4=h2fe6a88_5
  - libsdformat14=14.5.0=hb243517_0
  - libspral=2025.03.06=h39c1cf3_0
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=15.1.0=h4852527_4
  - libtasn1=4.20.0=hb9d3cd8_0
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.51.0=hb03c661_1
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.8=h04c0eec_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=h280c20c_1002
  - metis=5.1.0=hd0bcaf9_1007
  - mumps-include=5.7.3=h82cca05_10
  - mumps-seq=5.7.3=h27a6a8b_0
  - ncurses=6.5=h7934f7d_0
  - nettle=3.10.1=h4a9d5aa_0
  - numpy=1.26.4=py310hb13e2d6_0
  - octomap=1.9.8=h924138e_0
  - openssl=3.5.2=h26f9b46_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=25.0=py310h06a4308_0
  - pinocchio=3.1.0=py310hed69631_1
  - pip=25.2=pyh8b19718_0
  - proxsuite=0.7.2=py310h3788b33_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=hd6af730_0_cpython
  - python_abi=3.10=8_cp310
  - qhull=2020.2=h434a139_5
  - qhull-static=2020.2=h434a139_5
  - re2=2024.07.02=hdb19cb5_0
  - readline=8.3=hc2a1206_0
  - rhash=1.4.6=hb9d3cd8_1
  - ruby=3.4.2=he7af4c9_0
  - setuptools=78.1.1=py310h06a4308_0
  - simde=0.8.2=h84d6215_0
  - six=1.17.0=py310h06a4308_0
  - sqlite=3.50.4=hbc0de68_0
  - tinyxml2=10.0.0=h3f2d84a_2
  - tk=8.6.13=noxft_hd72426e_102
  - urdfdom=4.0.1=h2e5d1f2_2
  - urdfdom_headers=1.1.2=h84d6215_0
  - werkzeug=3.1.3=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.10.0
      - anytree==2.13.0
      - asttokens==3.0.0
      - attrs==25.3.0
      - boto3==1.40.18
      - botocore==1.40.18
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - click==8.2.1
      - cloudpickle==3.1.1
      - cmeel==0.57.3
      - cmeel-assimp==5.4.3.1
      - cmeel-boost==1.83.0
      - cmeel-console-bridge==1.0.2.3
      - cmeel-octomap==1.10.0
      - cmeel-qhull==8.0.2.1
      - cmeel-tinyxml==2.6.2.3
      - cmeel-urdfdom==3.1.1.1
      - cmeel-zlib==1.3.1
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - cyclonedds==0.10.2
      - cython==3.2.4
      - decorator==5.2.1
      - dex-retargeting==0.4.6
      - dm-control==1.0.36
      - dm-env==1.6
      - dm-tree==0.1.9
      - egl-probe==1.0.2
      - eigenpy==3.5.1
      - einops==0.8.1
      - etils==1.13.0
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - farama-notifications==0.0.4
      - fasteners==0.20
      - filelock==3.13.1
      - flaky==3.8.1
      - flatdict==4.0.1
      - fonttools==4.59.1
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glfw==2.10.0
      - grpcio==1.74.0
      - gym==0.23.1
      - gym-notices==0.1.0
      - gymnasium==1.2.0
      - h5py==3.14.0
      - hf-xet==1.1.8
      - hidapi==0.14.0.post2
      - huggingface-hub==0.34.4
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - inquirerpy==0.3.4
      - ipython==8.37.0
      - ipywidgets==8.1.5
      - isaac-lab-tutorial==0.1.0
      - isaaclab==0.45.8
      - isaaclab-assets==0.2.2
      - isaaclab-mimic==1.0.13
      - isaaclab-rl==0.2.4
      - isaaclab-tasks==0.10.47
      - isaacsim==4.5.0.0
      - isaacsim-app==4.5.0.0
      - isaacsim-asset==4.5.0.0
      - isaacsim-benchmark==4.5.0.0
      - isaacsim-code-editor==4.5.0.0
      - isaacsim-core==4.5.0.0
      - isaacsim-cortex==4.5.0.0
      - isaacsim-example==4.5.0.0
      - isaacsim-extscache-kit==4.5.0.0
      - isaacsim-extscache-kit-sdk==4.5.0.0
      - isaacsim-extscache-physics==4.5.0.0
      - isaacsim-gui==4.5.0.0
      - isaacsim-kernel==4.5.0.0
      - isaacsim-replicator==4.5.0.0
      - isaacsim-rl==4.5.0.0
      - isaacsim-robot==4.5.0.0
      - isaacsim-robot-motion==4.5.0.0
      - isaacsim-robot-setup==4.5.0.0
      - isaacsim-ros1==4.5.0.0
      - isaacsim-ros2==4.5.0.0
      - isaacsim-sensor==4.5.0.0
      - isaacsim-storage==4.5.0.0
      - isaacsim-template==4.5.0.0
      - isaacsim-test==4.5.0.0
      - isaacsim-utils==4.5.0.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - jmespath==1.0.1
      - joblib==1.5.1
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.4.1
      - junitparser==4.0.2
      - jupyterlab-widgets==3.0.15
      - keyboard==0.13.5
      - kiwisolver==1.4.9
      - labmaze==1.0.6
      - llvmlite==0.44.0
      - loop-rate-limiters==1.2.0
      - lxml==6.0.1
      - markdown==3.8.2
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - moviepy==2.2.1
      - mpmath==1.3.0
      - msgpack==1.1.1
      - mujoco==3.4.0
      - mujoco-py==2.1.2.14
      - networkx==3.3
      - newproject==0.1.0
      - nlopt==2.7.1
      - numba==0.61.2
      - nvidia-cublas-cu12==12.8.3.14
      - nvidia-cuda-cupti-cu12==12.8.57
      - nvidia-cuda-nvrtc-cu12==12.8.61
      - nvidia-cuda-runtime-cu12==12.8.57
      - nvidia-cudnn-cu12==9.7.1.26
      - nvidia-cufft-cu12==11.3.3.41
      - nvidia-cufile-cu12==1.13.0.11
      - nvidia-curand-cu12==10.3.9.55
      - nvidia-cusolver-cu12==11.7.2.55
      - nvidia-cusparse-cu12==12.5.7.53
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvtx-cu12==12.8.55
      - omegaconf==2.3.0
      - omniverse-kit==106.5.0.162521
      - onnx==1.19.0
      - opencv-python==4.11.0.86
      - osqp==0.6.7.post3
      - pandas==2.3.2
      - parso==0.8.5
      - pexpect==4.9.0
      - pfzy==0.3.4
      - pillow==11.2.1
      - pin==2.7.0
      - pin-pink==3.1.0
      - platformdirs==4.4.0
      - pluggy==1.6.0
      - prettytable==3.3.0
      - proglog==0.1.12
      - prompt-toolkit==3.0.51
      - protobuf==6.32.0
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==3.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygame==2.6.1
      - pyglet==1.5.31
      - pygments==2.19.2
      - pyopengl==3.1.10
      - pyparsing==3.2.3
      - pyperclip==1.9.0
      - pytest==8.4.1
      - pytest-mock==3.14.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pytransform3d==3.14.2
      - pytz==2025.2
      - pyyaml==6.0.2
      - qdldl==0.1.7.post5
      - qpsolvers==4.8.1
      - quadprog==0.1.13
      - ray==2.49.0
      - referencing==0.36.2
      - regex==2025.7.34
      - requests==2.32.5
      - rich==14.1.0
      - rich-click==1.9.1
      - rl-games==1.6.1
      - robomimic==0.4.0
      - rpds-py==0.27.0
      - rsl-rl-lib==2.3.3
      - s3transfer==0.13.1
      - safetensors==0.6.2
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - sentry-sdk==2.35.1
      - setproctitle==1.3.6
      - skrl==1.4.3
      - smmap==5.0.2
      - sniffio==1.3.1
      - stable-baselines3==2.7.0
      - stack-data==0.6.3
      - starlette==0.45.3
      - sympy==1.13.3
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tokenizers==0.21.4
      - toml==0.10.2
      - tomli==2.2.1
      - torch==2.7.0+cu128
      - torchvision==0.22.0+cu128
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.55.4
      - trimesh==4.7.4
      - triton==3.3.0
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - unitree-rl-lab==0.1.0
      - unitree-sdk2py==1.0.1
      - urllib3==2.5.0
      - wandb==0.21.1
      - warp-lang==1.8.1
      - wcwidth==0.2.13
      - widgetsnbextension==4.0.14
      - wrapt==2.0.1
      - zipp==3.23.0
prefix: /home/rl/anaconda3/envs/isaaclab
